baseurl = "https://blog.thopmedia.com"
defaultContentLanguage = "en"
languageCode = "en"
title = "Thop Blog"

# [services]
# [services.disqus]
# shortname = ""
[services.googleAnalytics]
ID = "G-QF9J7ESHD9"

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "img/global-background.jpg"
# backgroundImageDark = ""

author = "Nikhil Jayammagari"
description = "ThopBlog is a website where I share blogs based on my YouTube videos. It focuses on topics like tech, HomeLab setups, and servers. Each blog provides a detailed explanation of the video content with step-by-step guides. The goal is to help readers understand and apply the information easily."
avatar = "/img/avatar.png"
headerTitle = "Thop Blog"
# motto = "Transform Your Digital Presence with Our Innovative Solutions"

# footerBottomText = ""

rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

email = "contact@thopmedia.com"

siteStartYear = 2025

favicon = "/img/favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
# stickyNav = true
reorderNavItems = ["search", "about", "rss", "posts", "categories", "tags"]
collapseNavItems = ["posts", "categories", "tags", "about"]
# noDefaultSummaryCover = true
# showTableOfContents = true
showSummaryCoverInPost = true
# imageZoomableInPost = true
showPrevNextPost = true
# reorderShares = ["x", "facebook", "whatsapp"]

# [params.navItems]

# [params.twikoo]
# enabled = true
# envID = ""
# region = ""
# lang = ""

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyy-MM-dd"

[params.navItems]
github = { href = "https://github.com/ThopMedia/", target = "_blank", icon = "logo-github", title = "GitHub" }
#x = { href = "https://x.com/thopmedia/", target = "_blank", icon = "logo-x", title = "X" }
#facebook = { href = "https://www.facebook.com/thopmedia/", target = "_blank", icon = "logo-facebook", title = "Facebook" }
instagram = { href = "https://www.instagram.com/thopmedia/", target = "_blank", icon = "logo-instagram", title = "Instagram" }
linkedin = { href = "https://www.linkedin.com/in/nikhilreddyj/", target = "_blank", icon = "logo-linkedin", title = "LinkedIn" }