baseurl = "https://blog.thopmedia.com"
defaultContentLanguage = "en"
languageCode = "en"
title = "ThopBlog"

# [services]
# [services.disqus]
# shortname = ""
# [services.googleAnalytics]
# ID = ""

[params]
# zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "img/global-background.jpg"
# backgroundImageDark = ""

author = "Nikhil Jayammagari"
description = "WebDeveloper, Youtuber & Blogger"
avatar = "/img/avatar.png"
headerTitle = "ThopBlog"
# motto = "Transform Your Digital Presence with Our Innovative Solutions"

# footerBottomText = ""

# rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""

# waline = true
# walineServer = ""

email = "contact@thopmedia.com"

siteStartYear = 2025

favicon = "/img/favicon.ico"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
# stickyNav = true
reorderNavItems = ["search", "about", "rss", "posts", "categories", "tags"]
collapseNavItems = ["posts", "categories", "tags", "about"]
# noDefaultSummaryCover = true
# showTableOfContents = true
showSummaryCoverInPost = true
# imageZoomableInPost = true
showPrevNextPost = true
# reorderShares = ["x", "facebook", "whatsapp"]

# [params.navItems]

# [params.twikoo]
# enabled = true
# envID = ""
# region = ""
# lang = ""

# [params.advanced]
# customCSS = ["css/custom.css"]
# customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyy-MM-dd"

[params.navItems]
github = { href = "https://github.com/ThopMedia/", target = "_blank", icon = "logo-github", title = "GitHub" }
#x = { href = "https://x.com/thopmedia/", target = "_blank", icon = "logo-x", title = "X" }
#facebook = { href = "https://www.facebook.com/thopmedia/", target = "_blank", icon = "logo-facebook", title = "Facebook" }
instagram = { href = "https://www.instagram.com/thopmedia/", target = "_blank", icon = "logo-instagram", title = "Instagram" }
linkedin = { href = "https://www.linkedin.com/in/nikhilreddyj/", target = "_blank", icon = "logo-linkedin", title = "LinkedIn" }